In [1]:
import seaborn as sns
import pandas as pd
import plotly.express as px
import numpy as np

In [2]:
data = sns.load_dataset("tips")
data.head(5)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [25]:
features = ...
tip = ...

from sklearn import linear_model


LinearRegression(fit_intercept=False)

In [4]:
#f.predict([[]])

array([4.54192789])

In [36]:
#f.predict([[]])

array([14.37318953])

In [5]:
#add predictions to dataframe

In [19]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=data['total_bill'], y = data['tip'], 
                         mode = "markers", name = "actual"))
fig.add_trace(go.Scatter(x=data['total_bill'], y = data['prediction'], 
                         mode = "lines", name = "predicted"))
fig.update_layout(font_size = 20)

In [7]:
#get coefficients and intercept

array([0.1437319])

In [14]:
#fit with intercept

LinearRegression()

In [31]:
#f_w_int.predict([[100]])

array([11.42272135])

In [15]:
#get coefficient and intercept for new model

array([0.10502452])

In [22]:
data['prediction_with_intercept'] = f_w_int.predict(data[["total_bill"]])
fig = go.Figure()
fig.add_trace(go.Scatter(x=data['total_bill'], y = data['tip'], 
                         mode = "markers", name = "actual"))
fig.add_trace(go.Scatter(x=data['total_bill'], y = data['prediction'], 
                         mode = "lines", name = "prediction (b = 0)"))
fig.add_trace(go.Scatter(x=data['total_bill'], y = data['prediction_with_intercept'], 
                         mode = "lines", name = "predicted (b ≠ 0)"))
fig.update_layout(font_size = 20)

### Using Plotly

In [ ]:
fig = px.scatter(data, x = "total_bill", y = "tip", trendline = "ols",
          trendline_color_override="black")
fig.update_layout(font_size = 20)

In [37]:
fig = px.scatter(data, x = "total_bill", y = "tip", trendline = "ols",
          trendline_color_override="black")
results = px.get_trendline_results(fig)
results.px_fit_results.iloc[0].params

array([0.92026961, 0.10502452])

## Loss Functions

### Computing the L2 Loss and MSE

In [1]:
data = sns.load_dataset("tips")
data["prediction"] = f.predict(data[["total_bill"]])
data.head(5)

NameError: name 'sns' is not defined

In [ ]:
# add loss to the dataframe

In [ ]:
#compute the mean

In [ ]:
## or we can compute MSE directly from the outcome and predictions using mean_squared_error
from sklearn.metrics import mean_squared_error

### Understanding that MSE is a Function of One Variable

In [61]:
# replace the prediction column and L2 loss columns with the corresponding values for 20% tip

total_bill   tip     sex smoker   day    time  size  prediction  \
0         16.99  1.01  Female     No   Sun  Dinner     2       3.398   
1         10.34  1.66    Male     No   Sun  Dinner     3       2.068   
2         21.01  3.50    Male     No   Sun  Dinner     3       4.202   
3         23.68  3.31    Male     No   Sun  Dinner     2       4.736   
4         24.59  3.61  Female     No   Sun  Dinner     4       4.918   
..          ...   ...     ...    ...   ...     ...   ...         ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       5.806   
240       27.18  2.00  Female    Yes   Sat  Dinner     2       5.436   
241       22.67  2.00    Male    Yes   Sat  Dinner     2       4.534   
242       17.82  1.75    Male     No   Sat  Dinner     2       3.564   
243       18.78  3.00  Female     No  Thur  Dinner     2       3.756   

       L2_loss  
0     5.702544  
1     0.166464  
2     0.492804  
3     2.033476  
4     1.710864  
..         ...  
239   0.012996  
240  11.806096  
241   6.421156  
242   3.290596  
243   0.571536  

[244 rows x 9 columns]

In [62]:
# compute the mean_squared_error for 20% tip
mean_squared_error(data["prediction"], data["tip"])

2.667486278688525

In [ ]:
# compute error for a 20% tip on one line (without creating prediction and L2 loss column)

In [2]:
# compute error for various % tip values

In [ ]:
# define a function mse_given_theta as a function which takes theta
# and computes RMSE

In [ ]:
# create a list of thetas

In [3]:
# compute MSEs for those thetas

In [ ]:
# plot MSE vs theta, showing off how to set xaxis_title and yaxis_title

## Minimizing a Function Using Scipy Optimize

In [ ]:
import scipy.optimize

In [ ]:
# define g as the cube of x plus square of x minus 3 times x plus 2

In [ ]:
# try to minimize g manually

In [5]:
# use scipy.optimize.minimize and compare with wolfram alpha

## Multiple Linear Regression

In [157]:
# fit a model on total_bill and size

LinearRegression(fit_intercept=False)

In [159]:
#show coefficients

array([0.1007119 , 0.36209717])

In [160]:
# make a prediction for a table with $10 total bill and 3 people seated

array([2.09341054])

In [164]:
# compare predictions for f and f2 side by side in table

In [ ]:
# plot 3d data
px.scatter_3d(data, x = "total_bill", y = "size", z = "tip")

In [ ]:
# This code is not something we expect you to understand!
# It's just computing predictions for various bills and table sizes
table_bills, table_sizes = np.meshgrid(range(50), range(6))
tip_predictions = ( 0.1007119 * table_bills + 0.3621 * table_sizes)

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter3d(x = data["total_bill"], y = data["size"], z = data["tip"],
                         mode = "markers", name = "actual"))
fig.add_trace(go.Surface(x = table_bills, y = table_sizes, z = tip_predictions, name = "predicted"))
fig.show()

In [6]:
# compare MSE for f and f2 

### Using Non-numeric Features

In [7]:
# show rows from different days of the week
data = sns.load_dataset("tips")
data.iloc[[193, 90, 25, 26, 190], :]

NameError: name 'sns' is not defined

In [ ]:
# create a copy of the dataset that only has 3 features in order to keep things simple
three_features = ['total_bill', 'size', 'day']

three_feature_data = pd.DataFrame(data[three_features])
three_feature_data.head(5)

In [ ]:
# let's create "dummies" that represent whether it is thursday, friday, saturday, or sunday
dummies = pd.get_dummies(three_feature_data['day'])
dummies.iloc[[193, 90, 25, 26, 190], :]

In [ ]:
# concatenate the dummies table with three_feature_data
data_w_dummies = pd.concat([three_feature_data, dummies], axis=1)
data_w_dummies.iloc[[193, 90, 25, 26, 190], :]

In [ ]:
# The code below will crash since data_w_dummies includes a non-numeric feature
f_with_day = linear_model.LinearRegression(fit_intercept=False)
f_with_day.fit(data_w_dummies, tip)

In [ ]:
# drop the non-numeric column
del data_w_dummies["day"]
data_w_dummies.head(5)

In [ ]:
# fit the model
f_with_day = linear_model.LinearRegression(fit_intercept=False)
f_with_day.fit(data_w_dummies, tip)

In [ ]:
# get the coefficients

In [ ]:
# make prediction for a party of 3, with a $50 total bill, eating on a thursday

In [8]:
# make prediction for a party of 3 with a $50 total bill, eating on a saturday

In [ ]:
## compute MSE for 6 parameter model and compare to earlier

### Fitting Multiple Non-Numeric Conditions in Plotly

In [9]:
# create four separate plotly trendlines, one for each day of the week